# Generated by Django 4.2.3 on 2023-07-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('software', 'yazilim'), ('product', 'urun'), ('game', 'oyun'), ('book', 'kitap'), ('movie', 'film')], default='software', max_length=10),
        ),
    ]
