# Generated by Django 4.2.3 on 2023-07-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('software', 'Yazılım'), ('product', 'Ürün'), ('game', 'Oyun'), ('book', 'Kitap'), ('movie', 'Film')], default='software', max_length=10),
        ),
    ]
